# Cáº¥u hÃ¬nh káº¿t ná»i PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/booktify
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Cáº¥u hÃ¬nh Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Cáº¥u hÃ¬nh hiá»n thá» log chi tiáº¿t cho Spring Security (Debug mode)
logging.level.org.springframework.security=DEBUG
# logging.level.org.springframework=DEBUG
# logging.level.root=INFO

# Cáº¥u hÃ¬nh View Engine cho Spring MVC (JSP)
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hungdvce170162@fpt.edu.vn
spring.mail.password=yigmgxtkewsldqms

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cáº¥u hÃ¬nh giá»i háº¡n file upload vÃ  request kÃ­ch thÆ°á»c lá»n
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.file-size-threshold=2MB

# Cáº¥u hÃ¬nh xá»­ lÃ½ lá»i (404 handler) vÃ  ngoáº¡i lá» khÃ´ng tÃ¬m tháº¥y handler
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# Cáº¥u hÃ¬nh Session lÆ°u trong cÆ¡ sá» dá»¯ liá»u vÃ  thá»i gian háº¿t háº¡n
spring.session.store-type=jdbc
spring.session.jdbc.table-name=SPRING_SESSION
server.servlet.session.timeout=30m


# Spring sáº½ tá»± Äá»ng khá»i táº¡o báº£ng lÆ°u trá»¯ session náº¿u chÆ°a cÃ³
spring.session.jdbc.initialize-schema=always

# spring.session.jdbc.initialize-schema=always
#server.servlet.session.timeout
#spring.session.jdbc.table-name=SPRING_SESSION

server.port=8080

# Cấu hình Gmail SMTP (dùng chung cho Register và Forgot Password)
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.username=kienchung2107@gmail.com
mail.password=ieck ladt bohj ziya

